USE [master]
GO
/****** Object:  Database [TaskBoardDB]    Script Date: 5/6/2026 9:30:07 AM ******/
CREATE DATABASE [TaskBoardDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskBoardDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\TaskBoardDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskBoardDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\TaskBoardDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskBoardDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TaskBoardDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaskBoardDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaskBoardDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaskBoardDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaskBoardDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaskBoardDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaskBoardDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaskBoardDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaskBoardDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaskBoardDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaskBoardDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaskBoardDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaskBoardDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaskBoardDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaskBoardDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TaskBoardDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaskBoardDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaskBoardDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TaskBoardDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TaskBoardDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaskBoardDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TaskBoardDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TaskBoardDB] SET RECOVERY FULL 
GO
ALTER DATABASE [TaskBoardDB] SET  MULTI_USER 
GO
ALTER DATABASE [TaskBoardDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TaskBoardDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TaskBoardDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TaskBoardDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TaskBoardDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TaskBoardDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TaskBoardDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [TaskBoardDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TaskBoardDB]
GO
/****** Object:  Table [dbo].[Tasks]    Script Date: 5/6/2026 9:30:08 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[Priority] [nvarchar](10) NOT NULL,
	[Assignee] [nvarchar](10) NULL,
	[DueDate] [date] NULL,
	[Status] [nvarchar](20) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[UpdatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Tasks] ON 
GO
INSERT [dbo].[Tasks] ([Id], [Title], [Description], [Priority], [Assignee], [DueDate], [Status], [CreatedAt], [UpdatedAt]) VALUES (1, N'Connect React to API', N'Axios service + error handling', N'MEDIUM', N'CH', CAST(N'2025-05-08' AS Date), N'todo', CAST(N'2026-05-05T22:47:20.787' AS DateTime), NULL)
GO
INSERT [dbo].[Tasks] ([Id], [Title], [Description], [Priority], [Assignee], [DueDate], [Status], [CreatedAt], [UpdatedAt]) VALUES (2, N'Write README', N'Setup instructions and API docs', N'LOW', N'BO', CAST(N'2025-05-09' AS Date), N'todo', CAST(N'2026-05-05T22:47:20.787' AS DateTime), NULL)
GO
INSERT [dbo].[Tasks] ([Id], [Title], [Description], [Priority], [Assignee], [DueDate], [Status], [CreatedAt], [UpdatedAt]) VALUES (3, N'Build CRUD endpointsd', N'POST, GET, PUT, DELETE for tasks', N'HIGH', N'AL', CAST(N'2025-05-06' AS Date), N'inprogress', CAST(N'2026-05-06T07:25:06.713' AS DateTime), CAST(N'2026-05-06T07:25:06.713' AS DateTime))
GO
INSERT [dbo].[Tasks] ([Id], [Title], [Description], [Priority], [Assignee], [DueDate], [Status], [CreatedAt], [UpdatedAt]) VALUES (5, N'string', N'string', N'HIGH', N'yui', CAST(N'2026-05-06' AS Date), N'todo', CAST(N'2026-05-06T08:22:25.517' AS DateTime), CAST(N'2026-05-06T08:22:25.520' AS DateTime))
GO
INSERT [dbo].[Tasks] ([Id], [Title], [Description], [Priority], [Assignee], [DueDate], [Status], [CreatedAt], [UpdatedAt]) VALUES (18, N'fghj', N'', N'LOW', N'ME', CAST(N'2026-05-06' AS Date), N'done', CAST(N'2026-05-06T08:21:52.720' AS DateTime), NULL)
GO
SET IDENTITY_INSERT [dbo].[Tasks] OFF
GO
ALTER TABLE [dbo].[Tasks] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
USE [master]
GO
ALTER DATABASE [TaskBoardDB] SET  READ_WRITE 
GO
